FROM jrottenberg/ffmpeg:alpine

# Install MediaMTX (formerly known as rtsp-simple-server)
RUN wget https://github.com/bluenviron/mediamtx/releases/download/v1.11.0/mediamtx_v1.11.0_linux_amd64.tar.gz && \
    tar -xvf mediamtx_v1.11.0_linux_amd64.tar.gz && \
    mv mediamtx /usr/local/bin/ && \
    rm mediamtx_v1.11.0_linux_amd64.tar.gz

EXPOSE 8554

ENTRYPOINT ["/usr/local/bin/mediamtx"] 